import { makeRng } from '../../shared/math';

// "Reroute the fuse grid" — a lights-out puzzle. Pressing a node toggles it and
// its orthogonal neighbours; the circuit is restored when every node is lit.
// Generated by scrambling the solved (all-on) state, so it's always solvable;
// `scramble` lets tests reproduce a solution. Pure + seeded.

export interface FusePuzzle {
  size: number;
  start: boolean[]; // initial (scrambled) state, row-major
  scramble: number[]; // indices pressed to scramble from solved
}

export function press(size: number, state: boolean[], i: number): boolean[] {
  const s = state.slice();
  const r = Math.floor(i / size);
  const c = i % size;
  for (const [dr, dc] of [
    [0, 0],
    [1, 0],
    [-1, 0],
    [0, 1],
    [0, -1],
  ]) {
    const nr = r + dr;
    const nc = c + dc;
    if (nr >= 0 && nr < size && nc >= 0 && nc < size) s[nr * size + nc] = !s[nr * size + nc];
  }
  return s;
}

export function makeFuseGrid(seed: number, size = 3): FusePuzzle {
  const rng = makeRng(seed);
  const n = size * size;
  let state = new Array<boolean>(n).fill(true); // solved = all lit
  const scramble: number[] = [];
  let moves = 3 + Math.floor(rng() * 4);
  while (moves-- > 0) {
    const i = Math.floor(rng() * n);
    scramble.push(i);
    state = press(size, state, i);
  }
  if (state.every(Boolean)) {
    // guarantee it isn't already solved
    const i = Math.floor(rng() * n);
    scramble.push(i);
    state = press(size, state, i);
  }
  return { size, start: state, scramble };
}

export function isSolved(state: boolean[]): boolean {
  return state.every(Boolean);
}
